quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

quotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('about_author/<int:author_id>',
         views.about_author, name='about_author'),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
                                          name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                                           name='password_reset_complete'),
]

quotes/quotesapp/models.py
from django.db import models

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.name}'


class Author(models.Model):
    fullname = models.CharField(max_length=50, null=False)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    bio = models.TextField()

    def __str__(self):
        return f'{self.fullname}'


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Author, Quote, Tag


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25,
                     required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, max_length=2000,
                      required=True, widget=TextInput())
    author = ModelChoiceField(
        queryset=Author.objects.all(), widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=100, required=True, widget=TextInput)
    born_date = CharField(max_length=100, required=True, widget=TextInput)
    born_location = CharField(max_length=150, required=True, widget=TextInput)
    bio = CharField(max_length=4000, required=True, widget=TextInput)

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'bio']

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/quotesapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import QuoteForm, AuthorForm, TagForm
from .models import Author, Quote, Tag

# Create your views here.


def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quotesapp/index.html', {"quotes": quotes})


def tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/tags.html", {"form": form})

    return render(request, "quotesapp/tags.html", {"form": TagForm()})


def author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/author.html", {"form": form})

    return render(request, "quotesapp/author.html", {"form": AuthorForm()})


def quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(
                name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/quote.html", {"authors": authors, "tags": tags, "form": form})

    return render(request, "quotesapp/quote.html", {"authors": authors, "tags": tags, "form": QuoteForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    author = Author.objects.get(id=quote.author_id)

    return render(request, "quotesapp/detail.html", {"quote": quote, "author": author})


def about_author(request, author_id):
    author = Author.objects.get(id=author_id)

    return render(request, 'quotesapp/about_author.html', {"author": author})

quotes/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import LoginForm, RegisterForm

# Create your views here.


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotesapp:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotesapp:main')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

quotes/quotesapp/templates/quotesapp/about_author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="container-fluid">
    <p>
        <strong>{{ author.fullname }}</strong>
    </p>
    <p>
        Born date: {{ author.born_date }}
    </p>
    <p>
        Born in: {{ author.born_location }}
    </p>
    <p>
        Biography: {{ author.bio }}
    </p>
</div>

{% endblock %}

quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Author fullname:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
        <label>Author born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
        <label>Author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
        <label>Author biography:
            {{form.bio}}
        </label>
        <span>{{ form.errors.bio }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'noteapp/style.css' %}">
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            <ul>
                <li><a href="/" role="button"> Go back to the main page </a></li>
            </ul>
        </nav>
        {% block content %} {% endblock %}
    </main>
</body>

</html>

quotes/quotesapp/templates/quotesapp/detail.html
{% extends "quotesapp/base.html" %}

{% block content %}
{% load extract_tags %}

<div class="container-fluid">
    <p class="text">{{ quote.quote }}</p>
    <p>by <small class="author">{{ author.fullname }}</small></p>
    <p>Tags: <small> {{ quote.tags|tags }} </small></p>
</div>

{% endblock %}

quotes/quotesapp/templates/quotesapp/index.html
<!DOCTYPE html>
<html lang="en">

{% load extract_tags %}

<head>
    <meta charset="UTF-8" />
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
    </div>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body>
    <main>
        <div class="container">
            <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
                {% if user.is_authenticated %}
                <ul>
                    <li><a href="{% url 'quotesapp:author' %}" role="button">Add Author</a></li>
                    <li><a href="{% url 'quotesapp:quote' %}" role="button">Add Quote</a></li>
                    <li><a href="{% url 'quotesapp:tag' %}" role="button">Add Tag</a></li>
                </ul>
                <ul>
                    <li>Welcome <b>{{ user.username }}!</b></li>
                    <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                </ul>
                {% else %}
                <ul>
                    <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                    <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                </ul>
                {% endif %}
            </nav>

            {% for quote in quotes %}
            <li style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
                <ul><strong>{{ quote.quote }}</strong></ul>
                <ul>by <em>{{quote.author.fullname}}</em>
                    <a href="about_author/{{quote.author_id}}">(about)</a>
                </ul>
                <ul>tags: {{ quote.tags|tags }}</ul>
            </li>

            {% endfor %}
        </div>
    </main>
</body>


</html>

quotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Enter the quote:
            {{form.quote}}
        </label>
        <span>{{form.error.quote}}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{author.id}}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/tags.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/login.html
{% extends "quotesapp/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>

</form>

{% endblock %}

quotes/users/templates/users/password_reset.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Password reset complete!</h2>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
{% autoescape off %}

<body>
    <p>Hi {{ user.username }},</p>
    <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
    <p>
        <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
            {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
        </a>
    </p>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Thanks,</p>
    <p>The Our Team</p>
    {% endautoescape %}

quotes/users/templates/users/signup.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="container">
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}